// EXCHANGES
export const GET_EXCHANGES = 'GET_EXCHANGES';
export const GET_EXCHANGES_ERROR = 'GET_EXCHANGES_ERROR';

// UI
export const UI_LOADING = 'UI_LOADING'

// PREDICTION
export const GET_PREDICTION = 'GET_PREDICTION';
export const GET_PREDICTION_ERROR = 'GET_PREDICTION_ERROR';